CREATE TABLE arabica (
	import_index TEXT,
	species TEXT NULL,
	owner TEXT NULL,
	country_of_origin TEXT NULL,
	farm_name TEXT NULL,
	lot_number TEXT NULL,
	mill TEXT NULL,
	ico_number TEXT NULL,
	company TEXT NULL,
	altitude TEXT NULL,
	region TEXT NULL,
	producer TEXT NULL,
	number_of_bags INT NULL,
	bag_weight TEXT NULL,
	in_country_partner TEXT NULL,
	harvest_year TEXT NULL,
	grading_date TEXT NULL,
	owner_1 TEXT NULL,
	variety TEXT NULL,
	processing_method TEXT NULL,
	aroma FLOAT,
	flavor FLOAT,
	aftertaste FLOAT,
	acidity FLOAT,
	body FLOAT,
	balance FLOAT,
	uniformity FLOAT,
	clean_cup FLOAT,
	sweetness FLOAT,
	cupper_points FLOAT,
	total_cup_points FLOAT,
	moisture FLOAT,
	category_one_defects TEXT NULL,
	quakers FLOAT NULL,
	color TEXT NULL,
	category_two_defects TEXT NULL,
	expiration TEXT NULL,
	certification_body TEXT NULL,
	certification_address TEXT NULL,
	certification_contact TEXT NULL,
	unit_of_measurement TEXT NULL,
	altitude_low_meters FLOAT NULL,
	altitude_high_meters FLOAT NULL,
	altitude_mean_meters FLOAT NULL
);

